// Tipos con emoji y color
export const TIPOS = {
  normal:   { emoji: '⬜', color: '#A8A878', nombre: 'Normal' },
  fire:     { emoji: '🔥', color: '#F08030', nombre: 'Fuego' },
  water:    { emoji: '💧', color: '#6890F0', nombre: 'Agua' },
  electric: { emoji: '⚡', color: '#F8D030', nombre: 'Eléctrico' },
  grass:    { emoji: '🌿', color: '#78C850', nombre: 'Planta' },
  ice:      { emoji: '❄️', color: '#98D8D8', nombre: 'Hielo' },
  fighting: { emoji: '🥊', color: '#C03028', nombre: 'Lucha' },
  poison:   { emoji: '☠️', color: '#A040A0', nombre: 'Veneno' },
  ground:   { emoji: '🌍', color: '#E0C068', nombre: 'Tierra' },
  flying:   { emoji: '🦅', color: '#A890F0', nombre: 'Volador' },
  psychic:  { emoji: '🔮', color: '#F85888', nombre: 'Psíquico' },
  bug:      { emoji: '🐛', color: '#A8B820', nombre: 'Bicho' },
  rock:     { emoji: '🪨', color: '#B8A038', nombre: 'Roca' },
  ghost:    { emoji: '👻', color: '#705898', nombre: 'Fantasma' },
  dragon:   { emoji: '🐉', color: '#7038F8', nombre: 'Dragón' },
  dark:     { emoji: '🌑', color: '#705848', nombre: 'Siniestro' },
  steel:    { emoji: '⚙️', color: '#B8B8D0', nombre: 'Acero' },
  fairy:    { emoji: '✨', color: '#EE99AC', nombre: 'Hada' },
};

// Movimientos en español con tipo
export const MOVIMIENTOS = [
  { nombre: 'Placaje', tipo: 'normal' },
  { nombre: 'Gruñido', tipo: 'normal' },
  { nombre: 'Cola Látigo', tipo: 'normal' },
  { nombre: 'Rapidez', tipo: 'normal' },
  { nombre: 'Hipercolmillo', tipo: 'normal' },
  { nombre: 'Golpe Cabeza', tipo: 'normal' },
  { nombre: 'Doble Filo', tipo: 'normal' },
  { nombre: 'Corpulencia', tipo: 'normal' },
  { nombre: 'Amnesia', tipo: 'normal' },
  { nombre: 'Agilidad', tipo: 'psychic' },
  { nombre: 'Acua Jet', tipo: 'water' },
  { nombre: 'Acua Cola', tipo: 'water' },
  { nombre: 'Surf', tipo: 'water' },
  { nombre: 'Hidrobomba', tipo: 'water' },
  { nombre: 'Burbuja', tipo: 'water' },
  { nombre: 'Pistola Agua', tipo: 'water' },
  { nombre: 'Cascada', tipo: 'water' },
  { nombre: 'Rayo Burbuja', tipo: 'water' },
  { nombre: 'Buceo', tipo: 'water' },
  { nombre: 'Torbellino', tipo: 'water' },
  { nombre: 'Lluvia Danza', tipo: 'water' },
  { nombre: 'Absorber', tipo: 'grass' },
  { nombre: 'Megaagotar', tipo: 'grass' },
  { nombre: 'Gigadrenado', tipo: 'grass' },
  { nombre: 'Hoja Afilada', tipo: 'grass' },
  { nombre: 'Hoja Mágica', tipo: 'grass' },
  { nombre: 'Látigo Cepa', tipo: 'grass' },
  { nombre: 'Desarrollo', tipo: 'grass' },
  { nombre: 'Danza Pétalo', tipo: 'grass' },
  { nombre: 'Rayo Solar', tipo: 'grass' },
  { nombre: 'Síntesis', tipo: 'grass' },
  { nombre: 'Polvo Veneno', tipo: 'grass' },
  { nombre: 'Paralizador', tipo: 'grass' },
  { nombre: 'Somnífero', tipo: 'grass' },
  { nombre: 'Semilla Hierba', tipo: 'grass' },
  { nombre: 'Lanzallamas', tipo: 'fire' },
  { nombre: 'Ascuas', tipo: 'fire' },
  { nombre: 'Colmillo Ígneo', tipo: 'fire' },
  { nombre: 'Llamarada', tipo: 'fire' },
  { nombre: 'Rueda Fuego', tipo: 'fire' },
  { nombre: 'Pirotecnia', tipo: 'fire' },
  { nombre: 'Lanzafuego', tipo: 'fire' },
  { nombre: 'Danza Lluvia', tipo: 'fire' },
  { nombre: 'Día Soleado', tipo: 'fire' },
  { nombre: 'Impactrueno', tipo: 'electric' },
  { nombre: 'Rayo', tipo: 'electric' },
  { nombre: 'Trueno', tipo: 'electric' },
  { nombre: 'Colmillo Rayo', tipo: 'electric' },
  { nombre: 'Onda Trueno', tipo: 'electric' },
  { nombre: 'Chispa', tipo: 'electric' },
  { nombre: 'Voltio Cruel', tipo: 'electric' },
  { nombre: 'Bola Voltio', tipo: 'electric' },
  { nombre: 'Rayo Hielo', tipo: 'ice' },
  { nombre: 'Ventisca', tipo: 'ice' },
  { nombre: 'Alud', tipo: 'ice' },
  { nombre: 'Colmillo Hielo', tipo: 'ice' },
  { nombre: 'Viento Hielo', tipo: 'ice' },
  { nombre: 'Nieve Polvo', tipo: 'ice' },
  { nombre: 'Congelador', tipo: 'ice' },
  { nombre: 'Puño Hielo', tipo: 'ice' },
  { nombre: 'Golpe Karate', tipo: 'fighting' },
  { nombre: 'Patada Salto', tipo: 'fighting' },
  { nombre: 'Puño Dinámico', tipo: 'fighting' },
  { nombre: 'Machada', tipo: 'fighting' },
  { nombre: 'Inversión', tipo: 'fighting' },
  { nombre: 'A Bocajarro', tipo: 'fighting' },
  { nombre: 'Puño Cometa', tipo: 'fighting' },
  { nombre: 'Patada Baja', tipo: 'fighting' },
  { nombre: 'Foco Energía', tipo: 'fighting' },
  { nombre: 'Golpe Bajo', tipo: 'fighting' },
  { nombre: 'Ácido', tipo: 'poison' },
  { nombre: 'Bomba Lodo', tipo: 'poison' },
  { nombre: 'Lodo', tipo: 'poison' },
  { nombre: 'Picadura', tipo: 'poison' },
  { nombre: 'Colmillo Venen', tipo: 'poison' },
  { nombre: 'Tóxico', tipo: 'poison' },
  { nombre: 'Terremoto', tipo: 'ground' },
  { nombre: 'Fisura', tipo: 'ground' },
  { nombre: 'Excavar', tipo: 'ground' },
  { nombre: 'Golpe Arena', tipo: 'ground' },
  { nombre: 'Ataque Arena', tipo: 'ground' },
  { nombre: 'Tormenta Arena', tipo: 'ground' },
  { nombre: 'Tornado', tipo: 'flying' },
  { nombre: 'Vuelo', tipo: 'flying' },
  { nombre: 'Aerocuchilla', tipo: 'flying' },
  { nombre: 'Vendaval', tipo: 'flying' },
  { nombre: 'Acróbata', tipo: 'flying' },
  { nombre: 'Picado', tipo: 'flying' },
  { nombre: 'Ataque Ala', tipo: 'flying' },
  { nombre: 'Confusión', tipo: 'psychic' },
  { nombre: 'Psíquico', tipo: 'psychic' },
  { nombre: 'Psicocarga', tipo: 'psychic' },
  { nombre: 'Psicorayo', tipo: 'psychic' },
  { nombre: 'Teletransporte', tipo: 'psychic' },
  { nombre: 'Cambia Defensa', tipo: 'psychic' },
  { nombre: 'Poder Reserva', tipo: 'psychic' },
  { nombre: 'Premonición', tipo: 'psychic' },
  { nombre: 'Zumbido', tipo: 'bug' },
  { nombre: 'Tijera X', tipo: 'bug' },
  { nombre: 'Picadura', tipo: 'bug' },
  { nombre: 'Señal Trampa', tipo: 'bug' },
  { nombre: 'Lanzarrocas', tipo: 'rock' },
  { nombre: 'Pedrada', tipo: 'rock' },
  { nombre: 'Avalancha', tipo: 'rock' },
  { nombre: 'Roca Afilada', tipo: 'rock' },
  { nombre: 'Golpe Roca', tipo: 'rock' },
  { nombre: 'Tumba Rocas', tipo: 'rock' },
  { nombre: 'Pulimento', tipo: 'rock' },
  { nombre: 'Bola Sombra', tipo: 'ghost' },
  { nombre: 'Lanza Mugre', tipo: 'ghost' },
  { nombre: 'Maldición', tipo: 'ghost' },
  { nombre: 'Rencor', tipo: 'ghost' },
  { nombre: 'Danza Espectro', tipo: 'ghost' },
  { nombre: 'Colmillo Draco', tipo: 'dragon' },
  { nombre: 'Garra Dragón', tipo: 'dragon' },
  { nombre: 'Dragoaliento', tipo: 'dragon' },
  { nombre: 'Enfado Dragón', tipo: 'dragon' },
  { nombre: 'Pulso Dragón', tipo: 'dragon' },
  { nombre: 'Cometa Draco', tipo: 'dragon' },
  { nombre: 'Mordisco', tipo: 'dark' },
  { nombre: 'Buena Noche', tipo: 'dark' },
  { nombre: 'Golpe Bajo', tipo: 'dark' },
  { nombre: 'Triturar', tipo: 'dark' },
  { nombre: 'Acoso', tipo: 'dark' },
  { nombre: 'Cabeza Hierro', tipo: 'steel' },
  { nombre: 'Cola Férrea', tipo: 'steel' },
  { nombre: 'Garra Metal', tipo: 'steel' },
  { nombre: 'Defensa Férrea', tipo: 'steel' },
  { nombre: 'Onda Anómala', tipo: 'fairy' },
  { nombre: 'Voz Cautivadora', tipo: 'fairy' },
  { nombre: 'Beso Drenante', tipo: 'fairy' },
  { nombre: 'Luz de Luna', tipo: 'fairy' },
  { nombre: 'Seducción', tipo: 'normal' },
  { nombre: 'Hiperrrayo', tipo: 'normal' },
  { nombre: 'Giga Impacto', tipo: 'normal' },
  { nombre: 'Triturar', tipo: 'normal' },
  { nombre: 'Puño Trueno', tipo: 'electric' },
  { nombre: 'Puño Fuego', tipo: 'fire' },
  { nombre: 'Golpe', tipo: 'normal' },
  { nombre: 'Megagolpe', tipo: 'normal' },
  { nombre: 'Derribo', tipo: 'normal' },
  { nombre: 'Canto', tipo: 'normal' },
  { nombre: 'Supersónico', tipo: 'normal' },
  { nombre: 'Tornado', tipo: 'normal' },
  { nombre: 'Látigo', tipo: 'normal' },
  { nombre: 'Fortaleza', tipo: 'normal' },
  { nombre: 'Protección', tipo: 'normal' },
  { nombre: 'Detección', tipo: 'fighting' },
  { nombre: 'Descanso', tipo: 'psychic' },
  { nombre: 'Ronquido', tipo: 'normal' },
  { nombre: 'Sustituto', tipo: 'normal' },
  { nombre: 'Venganza', tipo: 'normal' },
  { nombre: 'Contraataque', tipo: 'fighting' },
  { nombre: 'Espejo', tipo: 'normal' },
  { nombre: 'Retroceso', tipo: 'normal' },
  { nombre: 'Represalia', tipo: 'normal' },
  { nombre: 'Robavida', tipo: 'normal' },
  { nombre: 'Drenado', tipo: 'normal' },
  { nombre: 'Prioridad', tipo: 'normal' },
  { nombre: 'Atajar', tipo: 'normal' },
  { nombre: 'Pulso Cura', tipo: 'normal' },
  { nombre: 'Don Natural', tipo: 'normal' },
  { nombre: 'Doble Golpe', tipo: 'normal' },
  { nombre: 'Triple Golpe', tipo: 'fighting' },
  { nombre: 'Patada Ígnea', tipo: 'fire' },
  { nombre: 'Patada Trueno', tipo: 'electric' },
  { nombre: 'Patada Hielo', tipo: 'ice' },
];

// Objetos en español con ID para sprite de PokéAPI
export const OBJETOS = [
  { nombre: 'Poción', id: 17 },
  { nombre: 'Superpoción', id: 26 },
  { nombre: 'Hiperpoción', id: 35 },
  { nombre: 'Poción Máxima', id: 38 },
  { nombre: 'Revivir', id: 28 },
  { nombre: 'Revivir Máximo', id: 39 },
  { nombre: 'Antiveneno', id: 18 },
  { nombre: 'Antídoto', id: 18 },
  { nombre: 'Despertar', id: 21 },
  { nombre: 'Cura Quemado', id: 19 },
  { nombre: 'Cura Hielo', id: 20 },
  { nombre: 'Cura Total', id: 27 },
  { nombre: 'Agua Fresca', id: 30 },
  { nombre: 'Soda', id: 31 },
  { nombre: 'Limonada', id: 32 },
  { nombre: 'Leche Moo-Moo', id: 33 },
  { nombre: 'Agua Mineral', id: 34 },
  { nombre: 'Éter', id: 36 },
  { nombre: 'Éter Máximo', id: 37 },
  { nombre: 'Elixir', id: 40 },
  { nombre: 'Elixir Máximo', id: 41 },
  { nombre: 'Polvo Despertar', id: 21 },
  { nombre: 'Baya Figy', id: 159 },
  { nombre: 'Baya Zidra', id: 180 },
  { nombre: 'Baya Persimon', id: 183 },
  { nombre: 'Baya Zanama', id: 185 },
  { nombre: 'Baya Aguav', id: 160 },
  { nombre: 'Baya Wiki', id: 161 },
  { nombre: 'Baya Iapapa', id: 162 },
  { nombre: 'Baya Mago', id: 163 },
  { nombre: 'Baya Pecha', id: 151 },
  { nombre: 'Baya Rawst', id: 152 },
  { nombre: 'Baya Aspear', id: 153 },
  { nombre: 'Baya Cheri', id: 149 },
  { nombre: 'Baya Chesto', id: 150 },
  { nombre: 'Baya Lum', id: 156 },
  { nombre: 'Baya Sitrus', id: 157 },
  { nombre: 'Baya Oran', id: 155 },
  { nombre: 'Baya Leppa', id: 154 },
  { nombre: 'Restos', id: 46 },
  { nombre: 'Cáscara Hierro', id: 232 },
  { nombre: 'Banda Focus', id: 229 },
  { nombre: 'Fajín Focus', id: 269 },
  { nombre: 'Orbe Vida', id: 247 },
  { nombre: 'Pañuelo Elegido', id: 220 },
  { nombre: 'Gafas Elegidas', id: 268 },
  { nombre: 'Banda Elegida', id: 221 },
  { nombre: 'Roca Lisa', id: 107 },
  { nombre: 'Roca Caliente', id: 108 },
  { nombre: 'Roca Húmeda', id: 109 },
  { nombre: 'Roca Helada', id: 110 },
  { nombre: 'Amplificador', id: 236 },
  { nombre: 'Placa Mente', id: 303 },
  { nombre: 'Placa Tóxica', id: 298 },
  { nombre: 'Placa Tierra', id: 299 },
  { nombre: 'Placa Piedra', id: 300 },
  { nombre: 'Placa Hierro', id: 309 },
  { nombre: 'Placa Llama', id: 297 },
  { nombre: 'Placa Cielo', id: 306 },
  { nombre: 'Placa Aguada', id: 296 },
  { nombre: 'Placa Verde', id: 295 },
  { nombre: 'Placa Helada', id: 302 },
  { nombre: 'Placa Puño', id: 301 },
  { nombre: 'Placa Voltio', id: 307 },
  { nombre: 'Placa Insecto', id: 308 },
  { nombre: 'Placa Dragón', id: 304 },
  { nombre: 'Placa Oscura', id: 305 },
  { nombre: 'Garra Dragón', id: 82 },
  { nombre: 'Carbón', id: 99 },
  { nombre: 'Imán', id: 100 },
  { nombre: 'Cucharada Torcida', id: 101 },
  { nombre: 'Escama Dragón', id: 82 },
  { nombre: 'Ojo Agudeza', id: 211 },
  { nombre: 'Lente Zoom', id: 276 },
  { nombre: 'Gafas Sabiduría', id: 267 },
  { nombre: 'Sobre Potencia', id: 249 },
  { nombre: 'Globo Aire', id: 278 },
  { nombre: 'Joya Voladora', id: 570 },
  { nombre: 'Semilla Evasión', id: 257 },
  { nombre: 'Roca Evolución', id: 80 },
  { nombre: 'Piedra Fuego', id: 80 },
  { nombre: 'Piedra Agua', id: 84 },
  { nombre: 'Piedra Trueno', id: 83 },
  { nombre: 'Piedra Hoja', id: 85 },
  { nombre: 'Piedra Lunar', id: 81 },
  { nombre: 'Piedra Hielo', id: 849 },
  { nombre: 'Piedra Amanecer', id: 446 },
  { nombre: 'Piedra Oscura', id: 447 },
  { nombre: 'Piedra Brillante', id: 448 },
  { nombre: 'Espejo Siniestro', id: 233 },
  { nombre: 'Capa Negra', id: 232 },
  { nombre: 'Veneno Suave', id: 234 },
  { nombre: 'Seda Suave', id: 235 },
  { nombre: 'Tierra Suelta', id: 236 },
  { nombre: 'Metal Suave', id: 239 },
];
