// AUTO-GENERADO — Movimientos y objetos completos en español

export const TIPO_IDS = {
  normal:1, fighting:2, flying:3, poison:4, ground:5, rock:6,
  bug:7, ghost:8, steel:9, fire:10, water:11, grass:12,
  electric:13, psychic:14, ice:15, dragon:16, dark:17, fairy:18
};

export const TIPO_COLORES = {
  normal:'#A8A878', fighting:'#C03028', flying:'#A890F0', poison:'#A040A0',
  ground:'#E0C068', rock:'#B8A038', bug:'#A8B820', ghost:'#705898',
  steel:'#B8B8D0', fire:'#F08030', water:'#6890F0', grass:'#78C850',
  electric:'#F8D030', psychic:'#F85888', ice:'#98D8D8', dragon:'#7038F8',
  dark:'#705848', fairy:'#EE99AC'
};

export const MOVIMIENTOS = [
  // NORMAL
  {"nombre":"Placaje","tipo":"normal","tipoId":1},
  {"nombre":"Gruñido","tipo":"normal","tipoId":1},
  {"nombre":"Cola Látigo","tipo":"normal","tipoId":1},
  {"nombre":"Rapidez","tipo":"normal","tipoId":1},
  {"nombre":"Hipercolmillo","tipo":"normal","tipoId":1},
  {"nombre":"Golpe Cabeza","tipo":"normal","tipoId":1},
  {"nombre":"Doble Filo","tipo":"normal","tipoId":1},
  {"nombre":"Corpulencia","tipo":"normal","tipoId":1},
  {"nombre":"Amnesia","tipo":"normal","tipoId":1},
  {"nombre":"Megagolpe","tipo":"normal","tipoId":1},
  {"nombre":"Hiperrrayo","tipo":"normal","tipoId":1},
  {"nombre":"Giga Impacto","tipo":"normal","tipoId":1},
  {"nombre":"Golpe","tipo":"normal","tipoId":1},
  {"nombre":"Derribo","tipo":"normal","tipoId":1},
  {"nombre":"Canto","tipo":"normal","tipoId":1},
  {"nombre":"Supersónico","tipo":"normal","tipoId":1},
  {"nombre":"Látigo","tipo":"normal","tipoId":1},
  {"nombre":"Fortaleza","tipo":"normal","tipoId":1},
  {"nombre":"Protección","tipo":"normal","tipoId":1},
  {"nombre":"Descanso","tipo":"normal","tipoId":1},
  {"nombre":"Ronquido","tipo":"normal","tipoId":1},
  {"nombre":"Sustituto","tipo":"normal","tipoId":1},
  {"nombre":"Venganza","tipo":"normal","tipoId":1},
  {"nombre":"Espejo","tipo":"normal","tipoId":1},
  {"nombre":"Retroceso","tipo":"normal","tipoId":1},
  {"nombre":"Represalia","tipo":"normal","tipoId":1},
  {"nombre":"Robavida","tipo":"normal","tipoId":1},
  {"nombre":"Doble Golpe","tipo":"normal","tipoId":1},
  {"nombre":"Ataque Rápido","tipo":"normal","tipoId":1},
  {"nombre":"Seducción","tipo":"normal","tipoId":1},
  {"nombre":"Golpe Cuerpo","tipo":"normal","tipoId":1},
  {"nombre":"Triturar","tipo":"normal","tipoId":1},
  {"nombre":"Pulso Cura","tipo":"normal","tipoId":1},
  {"nombre":"Don Natural","tipo":"normal","tipoId":1},
  {"nombre":"Rizo Defensa","tipo":"normal","tipoId":1},
  {"nombre":"Impresionar","tipo":"normal","tipoId":1},
  {"nombre":"Golpe Bis","tipo":"normal","tipoId":1},
  {"nombre":"Última Baza","tipo":"normal","tipoId":1},
  {"nombre":"Trampa Rocas","tipo":"normal","tipoId":1},
  {"nombre":"Cara Susto","tipo":"normal","tipoId":1},
  {"nombre":"Vozarrón","tipo":"normal","tipoId":1},
  {"nombre":"Señuelo","tipo":"normal","tipoId":1},
  {"nombre":"Golpe Bajo","tipo":"normal","tipoId":1},
  {"nombre":"Rayo Concentrado","tipo":"normal","tipoId":1},
  {"nombre":"Excitación","tipo":"normal","tipoId":1},
  {"nombre":"Reserva","tipo":"normal","tipoId":1},
  {"nombre":"Tragar","tipo":"normal","tipoId":1},
  {"nombre":"Escupir","tipo":"normal","tipoId":1},
  {"nombre":"Deseo","tipo":"normal","tipoId":1},
  {"nombre":"Ingesta","tipo":"normal","tipoId":1},
  {"nombre":"Reciclar","tipo":"normal","tipoId":1},
  {"nombre":"Bola Sombra","tipo":"ghost","tipoId":8},
  {"nombre":"Imitación","tipo":"normal","tipoId":1},
  {"nombre":"Copia","tipo":"normal","tipoId":1},
  {"nombre":"Transformación","tipo":"normal","tipoId":1},
  {"nombre":"Palomita","tipo":"normal","tipoId":1},
  {"nombre":"Encanto","tipo":"normal","tipoId":1},
  {"nombre":"Bofetón Lodo","tipo":"normal","tipoId":1},
  {"nombre":"Lanzamiento","tipo":"normal","tipoId":1},
  {"nombre":"Intercambio","tipo":"normal","tipoId":1},
  {"nombre":"Golpe Bajo","tipo":"normal","tipoId":1},
  {"nombre":"Puño Sombra","tipo":"ghost","tipoId":8},
  // FUEGO
  {"nombre":"Lanzallamas","tipo":"fire","tipoId":10},
  {"nombre":"Ascuas","tipo":"fire","tipoId":10},
  {"nombre":"Colmillo Ígneo","tipo":"fire","tipoId":10},
  {"nombre":"Llamarada","tipo":"fire","tipoId":10},
  {"nombre":"Rueda Fuego","tipo":"fire","tipoId":10},
  {"nombre":"Pirotecnia","tipo":"fire","tipoId":10},
  {"nombre":"Lanzafuego","tipo":"fire","tipoId":10},
  {"nombre":"Día Soleado","tipo":"fire","tipoId":10},
  {"nombre":"Puño Fuego","tipo":"fire","tipoId":10},
  {"nombre":"Patada Ígnea","tipo":"fire","tipoId":10},
  {"nombre":"Defensa Ígnea","tipo":"fire","tipoId":10},
  {"nombre":"Nitrocarga","tipo":"fire","tipoId":10},
  {"nombre":"Sofoco","tipo":"fire","tipoId":10},
  {"nombre":"Humareda","tipo":"fire","tipoId":10},
  {"nombre":"Giro Fuego","tipo":"fire","tipoId":10},
  {"nombre":"Colmillo Ígneo","tipo":"fire","tipoId":10},
  {"nombre":"Vendetta","tipo":"fire","tipoId":10},
  // AGUA
  {"nombre":"Surf","tipo":"water","tipoId":11},
  {"nombre":"Hidrobomba","tipo":"water","tipoId":11},
  {"nombre":"Burbuja","tipo":"water","tipoId":11},
  {"nombre":"Pistola Agua","tipo":"water","tipoId":11},
  {"nombre":"Cascada","tipo":"water","tipoId":11},
  {"nombre":"Rayo Burbuja","tipo":"water","tipoId":11},
  {"nombre":"Buceo","tipo":"water","tipoId":11},
  {"nombre":"Torbellino","tipo":"water","tipoId":11},
  {"nombre":"Lluvia Danza","tipo":"water","tipoId":11},
  {"nombre":"Acua Jet","tipo":"water","tipoId":11},
  {"nombre":"Acua Cola","tipo":"water","tipoId":11},
  {"nombre":"Pulso Agua","tipo":"water","tipoId":11},
  {"nombre":"Chorro de Agua","tipo":"water","tipoId":11},
  {"nombre":"Nado Sombrío","tipo":"water","tipoId":11},
  {"nombre":"Cañón Hídrico","tipo":"water","tipoId":11},
  {"nombre":"Liquidación","tipo":"water","tipoId":11},
  {"nombre":"Golpe Razor","tipo":"water","tipoId":11},
  // PLANTA
  {"nombre":"Absorber","tipo":"grass","tipoId":12},
  {"nombre":"Megaagotar","tipo":"grass","tipoId":12},
  {"nombre":"Gigadrenado","tipo":"grass","tipoId":12},
  {"nombre":"Hoja Afilada","tipo":"grass","tipoId":12},
  {"nombre":"Hoja Mágica","tipo":"grass","tipoId":12},
  {"nombre":"Látigo Cepa","tipo":"grass","tipoId":12},
  {"nombre":"Desarrollo","tipo":"grass","tipoId":12},
  {"nombre":"Danza Pétalo","tipo":"grass","tipoId":12},
  {"nombre":"Rayo Solar","tipo":"grass","tipoId":12},
  {"nombre":"Síntesis","tipo":"grass","tipoId":12},
  {"nombre":"Polvo Veneno","tipo":"grass","tipoId":12},
  {"nombre":"Paralizador","tipo":"grass","tipoId":12},
  {"nombre":"Somnífero","tipo":"grass","tipoId":12},
  {"nombre":"Semilla Hierba","tipo":"grass","tipoId":12},
  {"nombre":"Hoja Aguda","tipo":"grass","tipoId":12},
  {"nombre":"Tormenta Floral","tipo":"grass","tipoId":12},
  {"nombre":"Golpe Hierba","tipo":"grass","tipoId":12},
  {"nombre":"Cuchilla Hierba","tipo":"grass","tipoId":12},
  {"nombre":"Energibola","tipo":"grass","tipoId":12},
  {"nombre":"Arraigo","tipo":"grass","tipoId":12},
  {"nombre":"Esporagodón","tipo":"grass","tipoId":12},
  {"nombre":"Tormenta Hoja","tipo":"grass","tipoId":12},
  // ELÉCTRICO
  {"nombre":"Impactrueno","tipo":"electric","tipoId":13},
  {"nombre":"Rayo","tipo":"electric","tipoId":13},
  {"nombre":"Trueno","tipo":"electric","tipoId":13},
  {"nombre":"Colmillo Rayo","tipo":"electric","tipoId":13},
  {"nombre":"Onda Trueno","tipo":"electric","tipoId":13},
  {"nombre":"Chispa","tipo":"electric","tipoId":13},
  {"nombre":"Voltio Cruel","tipo":"electric","tipoId":13},
  {"nombre":"Bola Voltio","tipo":"electric","tipoId":13},
  {"nombre":"Puño Trueno","tipo":"electric","tipoId":13},
  {"nombre":"Patada Trueno","tipo":"electric","tipoId":13},
  {"nombre":"Electromalla","tipo":"electric","tipoId":13},
  {"nombre":"Levitón","tipo":"electric","tipoId":13},
  {"nombre":"Magnetismo","tipo":"electric","tipoId":13},
  {"nombre":"Rayo Carga","tipo":"electric","tipoId":13},
  {"nombre":"Carga","tipo":"electric","tipoId":13},
  // HIELO
  {"nombre":"Rayo Hielo","tipo":"ice","tipoId":15},
  {"nombre":"Ventisca","tipo":"ice","tipoId":15},
  {"nombre":"Alud","tipo":"ice","tipoId":15},
  {"nombre":"Colmillo Hielo","tipo":"ice","tipoId":15},
  {"nombre":"Viento Hielo","tipo":"ice","tipoId":15},
  {"nombre":"Nieve Polvo","tipo":"ice","tipoId":15},
  {"nombre":"Congelador","tipo":"ice","tipoId":15},
  {"nombre":"Puño Hielo","tipo":"ice","tipoId":15},
  {"nombre":"Patada Hielo","tipo":"ice","tipoId":15},
  {"nombre":"Granizo","tipo":"ice","tipoId":15},
  {"nombre":"Nieve Arenosa","tipo":"ice","tipoId":15},
  {"nombre":"Estalactita","tipo":"ice","tipoId":15},
  // LUCHA
  {"nombre":"Golpe Karate","tipo":"fighting","tipoId":2},
  {"nombre":"Patada Salto","tipo":"fighting","tipoId":2},
  {"nombre":"Puño Dinámico","tipo":"fighting","tipoId":2},
  {"nombre":"Machada","tipo":"fighting","tipoId":2},
  {"nombre":"Inversión","tipo":"fighting","tipoId":2},
  {"nombre":"A Bocajarro","tipo":"fighting","tipoId":2},
  {"nombre":"Puño Cometa","tipo":"fighting","tipoId":2},
  {"nombre":"Patada Baja","tipo":"fighting","tipoId":2},
  {"nombre":"Foco Energía","tipo":"fighting","tipoId":2},
  {"nombre":"Contraataque","tipo":"fighting","tipoId":2},
  {"nombre":"Detección","tipo":"fighting","tipoId":2},
  {"nombre":"Triple Golpe","tipo":"fighting","tipoId":2},
  {"nombre":"Patada Ígnea","tipo":"fighting","tipoId":2},
  {"nombre":"Onda Vacía","tipo":"fighting","tipoId":2},
  {"nombre":"Tajo Cruzado","tipo":"fighting","tipoId":2},
  {"nombre":"Patada Salto Alt.","tipo":"fighting","tipoId":2},
  {"nombre":"Golpe Bajo Lucha","tipo":"fighting","tipoId":2},
  {"nombre":"Combate","tipo":"fighting","tipoId":2},
  {"nombre":"Vendaval Lucha","tipo":"fighting","tipoId":2},
  {"nombre":"Palmeo","tipo":"fighting","tipoId":2},
  // VENENO
  {"nombre":"Ácido","tipo":"poison","tipoId":4},
  {"nombre":"Bomba Lodo","tipo":"poison","tipoId":4},
  {"nombre":"Lodo","tipo":"poison","tipoId":4},
  {"nombre":"Colmillo Venenoso","tipo":"poison","tipoId":4},
  {"nombre":"Tóxico","tipo":"poison","tipoId":4},
  {"nombre":"Gas Venenoso","tipo":"poison","tipoId":4},
  {"nombre":"Agujón","tipo":"poison","tipoId":4},
  {"nombre":"Bomba Ácida","tipo":"poison","tipoId":4},
  {"nombre":"Niebla Venenosa","tipo":"poison","tipoId":4},
  {"nombre":"Contaminación","tipo":"poison","tipoId":4},
  // TIERRA
  {"nombre":"Terremoto","tipo":"ground","tipoId":5},
  {"nombre":"Fisura","tipo":"ground","tipoId":5},
  {"nombre":"Excavar","tipo":"ground","tipoId":5},
  {"nombre":"Golpe Arena","tipo":"ground","tipoId":5},
  {"nombre":"Ataque Arena","tipo":"ground","tipoId":5},
  {"nombre":"Tormenta Arena","tipo":"ground","tipoId":5},
  {"nombre":"Bofetón Arena","tipo":"ground","tipoId":5},
  {"nombre":"Tumba","tipo":"ground","tipoId":5},
  {"nombre":"Lanzamiento Tierra","tipo":"ground","tipoId":5},
  // VOLADOR
  {"nombre":"Tornado","tipo":"flying","tipoId":3},
  {"nombre":"Vuelo","tipo":"flying","tipoId":3},
  {"nombre":"Aerocuchilla","tipo":"flying","tipoId":3},
  {"nombre":"Vendaval","tipo":"flying","tipoId":3},
  {"nombre":"Acróbata","tipo":"flying","tipoId":3},
  {"nombre":"Picado","tipo":"flying","tipoId":3},
  {"nombre":"Ataque Ala","tipo":"flying","tipoId":3},
  {"nombre":"Tajo Aéreo","tipo":"flying","tipoId":3},
  {"nombre":"Danza Pluma","tipo":"flying","tipoId":3},
  {"nombre":"Pájaro Osado","tipo":"flying","tipoId":3},
  {"nombre":"Ciclón","tipo":"flying","tipoId":3},
  {"nombre":"Remolino","tipo":"flying","tipoId":3},
  {"nombre":"Viento Afín","tipo":"flying","tipoId":3},
  // PSÍQUICO
  {"nombre":"Confusión","tipo":"psychic","tipoId":14},
  {"nombre":"Psíquico","tipo":"psychic","tipoId":14},
  {"nombre":"Psicocarga","tipo":"psychic","tipoId":14},
  {"nombre":"Psicorayo","tipo":"psychic","tipoId":14},
  {"nombre":"Teletransporte","tipo":"psychic","tipoId":14},
  {"nombre":"Poder Reserva","tipo":"psychic","tipoId":14},
  {"nombre":"Premonición","tipo":"psychic","tipoId":14},
  {"nombre":"Agilidad","tipo":"psychic","tipoId":14},
  {"nombre":"Descanso","tipo":"psychic","tipoId":14},
  {"nombre":"Barrera","tipo":"psychic","tipoId":14},
  {"nombre":"Amnesia","tipo":"psychic","tipoId":14},
  {"nombre":"Hipnosis","tipo":"psychic","tipoId":14},
  {"nombre":"Meditación","tipo":"psychic","tipoId":14},
  {"nombre":"Cambio Defensa","tipo":"psychic","tipoId":14},
  {"nombre":"Psicopulso","tipo":"psychic","tipoId":14},
  {"nombre":"Premonición","tipo":"psychic","tipoId":14},
  {"nombre":"Psicocorte","tipo":"psychic","tipoId":14},
  {"nombre":"Truco","tipo":"psychic","tipoId":14},
  {"nombre":"Intercambio Poderes","tipo":"psychic","tipoId":14},
  // BICHO
  {"nombre":"Zumbido","tipo":"bug","tipoId":7},
  {"nombre":"Tijera X","tipo":"bug","tipoId":7},
  {"nombre":"Picadura","tipo":"bug","tipoId":7},
  {"nombre":"Señal Trampa","tipo":"bug","tipoId":7},
  {"nombre":"Ataque Polilla","tipo":"bug","tipoId":7},
  {"nombre":"Picotazo","tipo":"bug","tipoId":7},
  {"nombre":"Beso Drenante","tipo":"bug","tipoId":7},
  {"nombre":"Estoicismo","tipo":"bug","tipoId":7},
  {"nombre":"Telaraña","tipo":"bug","tipoId":7},
  {"nombre":"Pegamento","tipo":"bug","tipoId":7},
  {"nombre":"Chispazo Bicho","tipo":"bug","tipoId":7},
  {"nombre":"Invasión","tipo":"bug","tipoId":7},
  {"nombre":"Tajo Bug","tipo":"bug","tipoId":7},
  {"nombre":"Zumbido Bicho","tipo":"bug","tipoId":7},
  {"nombre":"Megacuerno","tipo":"bug","tipoId":7},
  {"nombre":"Aguijón Venenoso","tipo":"bug","tipoId":7},
  // ROCA
  {"nombre":"Lanzarrocas","tipo":"rock","tipoId":6},
  {"nombre":"Pedrada","tipo":"rock","tipoId":6},
  {"nombre":"Avalancha","tipo":"rock","tipoId":6},
  {"nombre":"Roca Afilada","tipo":"rock","tipoId":6},
  {"nombre":"Golpe Roca","tipo":"rock","tipoId":6},
  {"nombre":"Tumba Rocas","tipo":"rock","tipoId":6},
  {"nombre":"Pulimento","tipo":"rock","tipoId":6},
  {"nombre":"Alud Rocas","tipo":"rock","tipoId":6},
  {"nombre":"Piedra Afilada","tipo":"rock","tipoId":6},
  {"nombre":"Trampa Rocas","tipo":"rock","tipoId":6},
  // FANTASMA
  {"nombre":"Bola Sombra","tipo":"ghost","tipoId":8},
  {"nombre":"Lanza Mugre","tipo":"ghost","tipoId":8},
  {"nombre":"Maldición","tipo":"ghost","tipoId":8},
  {"nombre":"Rencor","tipo":"ghost","tipoId":8},
  {"nombre":"Danza Espectro","tipo":"ghost","tipoId":8},
  {"nombre":"Puño Sombra","tipo":"ghost","tipoId":8},
  {"nombre":"Golpe Fantasma","tipo":"ghost","tipoId":8},
  {"nombre":"Hipnosis Sombría","tipo":"ghost","tipoId":8},
  // DRAGÓN
  {"nombre":"Colmillo Draco","tipo":"dragon","tipoId":16},
  {"nombre":"Garra Dragón","tipo":"dragon","tipoId":16},
  {"nombre":"Dragoaliento","tipo":"dragon","tipoId":16},
  {"nombre":"Enfado Dragón","tipo":"dragon","tipoId":16},
  {"nombre":"Pulso Dragón","tipo":"dragon","tipoId":16},
  {"nombre":"Cometa Draco","tipo":"dragon","tipoId":16},
  {"nombre":"Danza Dragón","tipo":"dragon","tipoId":16},
  {"nombre":"Cola Dragón","tipo":"dragon","tipoId":16},
  {"nombre":"Latido Dragón","tipo":"dragon","tipoId":16},
  // SINIESTRO
  {"nombre":"Mordisco","tipo":"dark","tipoId":17},
  {"nombre":"Buena Noche","tipo":"dark","tipoId":17},
  {"nombre":"Triturar","tipo":"dark","tipoId":17},
  {"nombre":"Acoso","tipo":"dark","tipoId":17},
  {"nombre":"Golpe Bajo","tipo":"dark","tipoId":17},
  {"nombre":"Embargo","tipo":"dark","tipoId":17},
  {"nombre":"Tinieblas","tipo":"dark","tipoId":17},
  {"nombre":"Paliza","tipo":"dark","tipoId":17},
  {"nombre":"Vendetta Oscura","tipo":"dark","tipoId":17},
  {"nombre":"Ciclo Sombrío","tipo":"dark","tipoId":17},
  // ACERO
  {"nombre":"Cabeza Hierro","tipo":"steel","tipoId":9},
  {"nombre":"Cola Férrea","tipo":"steel","tipoId":9},
  {"nombre":"Garra Metal","tipo":"steel","tipoId":9},
  {"nombre":"Defensa Férrea","tipo":"steel","tipoId":9},
  {"nombre":"Bomba Magnética","tipo":"steel","tipoId":9},
  {"nombre":"Guillotina Metálica","tipo":"steel","tipoId":9},
  {"nombre":"Puño Meteoro","tipo":"steel","tipoId":9},
  {"nombre":"Espada Santa","tipo":"steel","tipoId":9},
  // HADA
  {"nombre":"Onda Anómala","tipo":"fairy","tipoId":18},
  {"nombre":"Voz Cautivadora","tipo":"fairy","tipoId":18},
  {"nombre":"Beso Drenante","tipo":"fairy","tipoId":18},
  {"nombre":"Luz de Luna","tipo":"fairy","tipoId":18},
  {"nombre":"Seducción","tipo":"fairy","tipoId":18},
  {"nombre":"Polvo Mágico","tipo":"fairy","tipoId":18},
  {"nombre":"Martillo Bello","tipo":"fairy","tipoId":18},
  {"nombre":"Brillo Mágico","tipo":"fairy","tipoId":18},
  {"nombre":"Voz Mágica","tipo":"fairy","tipoId":18}
];


export const OBJETOS = [
  {"nombre":"Poción","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/potion.png"},
  {"nombre":"Superpoción","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/super-potion.png"},
  {"nombre":"Hiperpoción","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hyper-potion.png"},
  {"nombre":"Poción Máxima","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-potion.png"},
  {"nombre":"Revivir","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/revive.png"},
  {"nombre":"Revivir Máximo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-revive.png"},
  {"nombre":"Antiveneno","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/antidote.png"},
  {"nombre":"Despertar","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/awakening.png"},
  {"nombre":"Cura Quemado","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/burn-heal.png"},
  {"nombre":"Cura Hielo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-heal.png"},
  {"nombre":"Cura Parálisis","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/paralyze-heal.png"},
  {"nombre":"Cura Total","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-heal.png"},
  {"nombre":"Restauración Total","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-restore.png"},
  {"nombre":"Agua Fresca","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fresh-water.png"},
  {"nombre":"Soda","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/soda-pop.png"},
  {"nombre":"Limonada","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lemonade.png"},
  {"nombre":"Leche Moo-Moo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moomoo-milk.png"},
  {"nombre":"Éter","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ether.png"},
  {"nombre":"Éter Máximo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-ether.png"},
  {"nombre":"Elixir","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/elixir.png"},
  {"nombre":"Elixir Máximo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-elixir.png"},
  {"nombre":"Mineral Raro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rare-candy.png"},
  {"nombre":"PP Máx","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pp-max.png"},
  {"nombre":"PP Plus","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pp-up.png"},

  {"nombre":"Baya Aguav","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aguav-berry.png"},
  {"nombre":"Baya Apicot","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/apicot-berry.png"},
  {"nombre":"Baya Aspear","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aspear-berry.png"},
  {"nombre":"Baya Babiri","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/babiri-berry.png"},
  {"nombre":"Baya Belue","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/belue-berry.png"},
  {"nombre":"Baya Bluk","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/bluk-berry.png"},
  {"nombre":"Baya Charti","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charti-berry.png"},
  {"nombre":"Baya Cheri","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/cheri-berry.png"},
  {"nombre":"Baya Chesto","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/chesto-berry.png"},
  {"nombre":"Baya Chilan","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/chilan-berry.png"},
  {"nombre":"Baya Chople","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/chople-berry.png"},
  {"nombre":"Baya Coba","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coba-berry.png"},
  {"nombre":"Baya Colbur","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/colbur-berry.png"},
  {"nombre":"Baya Custap","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/custap-berry.png"},
  {"nombre":"Baya Durin","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/durin-berry.png"},
  {"nombre":"Baya Enigma","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/enigma-berry.png"},
  {"nombre":"Baya Espelon","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/espelon-berry.png"},
  {"nombre":"Baya Figy","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/figy-berry.png"},
  {"nombre":"Baya Ganlon","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ganlon-berry.png"},
  {"nombre":"Baya Grepa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/grepa-berry.png"},
  {"nombre":"Baya Haban","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/haban-berry.png"},
  {"nombre":"Baya Iapapa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/iapapa-berry.png"},
  {"nombre":"Baya Jaboca","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/jaboca-berry.png"},
  {"nombre":"Baya Kasib","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kasib-berry.png"},
  {"nombre":"Baya Kebia","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kebia-berry.png"},
  {"nombre":"Baya Kelpsy","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kelpsy-berry.png"},
  {"nombre":"Baya Lansat","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lansat-berry.png"},
  {"nombre":"Baya Leppa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leppa-berry.png"},
  {"nombre":"Baya Liechi","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/liechi-berry.png"},
  {"nombre":"Baya Lum","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lum-berry.png"},
  {"nombre":"Baya Mago","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mago-berry.png"},
  {"nombre":"Baya Magost","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magost-berry.png"},
  {"nombre":"Baya Micle","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/micle-berry.png"},
  {"nombre":"Baya Nanab","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nanab-berry.png"},
  {"nombre":"Baya Nomel","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nomel-berry.png"},
  {"nombre":"Baya Occa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/occa-berry.png"},
  {"nombre":"Baya Oran","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/oran-berry.png"},
  {"nombre":"Baya Pamtre","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pamtre-berry.png"},
  {"nombre":"Baya Passho","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/passho-berry.png"},
  {"nombre":"Baya Payapa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/payapa-berry.png"},
  {"nombre":"Baya Pecha","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pecha-berry.png"},
  {"nombre":"Baya Persim","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/persim-berry.png"},
  {"nombre":"Baya Petaya","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/petaya-berry.png"},
  {"nombre":"Baya Pinap","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pinap-berry.png"},
  {"nombre":"Baya Pomeg","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pomeg-berry.png"},
  {"nombre":"Baya Qualot","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/qualot-berry.png"},
  {"nombre":"Baya Rabuta","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rabuta-berry.png"},
  {"nombre":"Baya Rawst","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rawst-berry.png"},
  {"nombre":"Baya Razz","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razz-berry.png"},
  {"nombre":"Baya Rindo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rindo-berry.png"},
  {"nombre":"Baya Roseli","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/roseli-berry.png"},
  {"nombre":"Baya Salac","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/salac-berry.png"},
  {"nombre":"Baya Shuca","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shuca-berry.png"},
  {"nombre":"Baya Sitrus","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sitrus-berry.png"},
  {"nombre":"Baya Spelon","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/spelon-berry.png"},
  {"nombre":"Baya Starf","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/starf-berry.png"},
  {"nombre":"Baya Tamato","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tamato-berry.png"},
  {"nombre":"Baya Tanga","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tanga-berry.png"},
  {"nombre":"Baya Wacan","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wacan-berry.png"},
  {"nombre":"Baya Watmel","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/watmel-berry.png"},
  {"nombre":"Baya Wepear","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wepear-berry.png"},
  {"nombre":"Baya Wiki","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wiki-berry.png"},
  {"nombre":"Baya Yache","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/yache-berry.png"},

  {"nombre":"Piedra Fuego","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png"},
  {"nombre":"Piedra Agua","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/water-stone.png"},
  {"nombre":"Piedra Trueno","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thunder-stone.png"},
  {"nombre":"Piedra Hoja","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png"},
  {"nombre":"Piedra Lunar","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moon-stone.png"},
  {"nombre":"Piedra Solar","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sun-stone.png"},
  {"nombre":"Piedra Hielo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-stone.png"},
  {"nombre":"Piedra Amanecer","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dawn-stone.png"},
  {"nombre":"Piedra Oscura","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-stone.png"},
  {"nombre":"Piedra Brillante","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shiny-stone.png"},
  {"nombre":"Mineral Extraño","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/oval-stone.png"},
  {"nombre":"Trozo de Hielo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/never-melt-ice.png"},

  {"nombre":"Restos","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leftovers.png"},
  {"nombre":"Banda Focus","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/focus-band.png"},
  {"nombre":"Fajín Focus","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/focus-sash.png"},
  {"nombre":"Orbe Vida","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/life-orb.png"},
  {"nombre":"Pañuelo Elegido","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-scarf.png"},
  {"nombre":"Gafas Elegidas","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-specs.png"},
  {"nombre":"Banda Elegida","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-band.png"},
  {"nombre":"Globo Aire","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/air-balloon.png"},
  {"nombre":"Cáscara Hierro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/iron-ball.png"},
  {"nombre":"Roca Lisa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/smooth-rock.png"},
  {"nombre":"Roca Caliente","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heat-rock.png"},
  {"nombre":"Roca Húmeda","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/damp-rock.png"},
  {"nombre":"Roca Helada","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/icy-rock.png"},
  {"nombre":"Amplificador","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metronome.png"},
  {"nombre":"Sobre Potencia","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png"},
  {"nombre":"Lente Zoom","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/zoom-lens.png"},
  {"nombre":"Botón Salida","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/eject-button.png"},
  {"nombre":"Cinta Protectora","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/safety-goggles.png"},

  {"nombre":"Garra Dragón","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dragon-fang.png"},
  {"nombre":"Carbón","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charcoal.png"},
  {"nombre":"Imán","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magnet.png"},
  {"nombre":"Cucharada Torcida","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/twisted-spoon.png"},
  {"nombre":"Ojo Agudeza","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sharp-beak.png"},
  {"nombre":"Gafas Sabiduría","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wise-glasses.png"},
  {"nombre":"Espejo Siniestro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dark-gem.png"},
  {"nombre":"Veneno Suave","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/poison-barb.png"},
  {"nombre":"Seda Suave","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/silk-scarf.png"},
  {"nombre":"Tierra Suelta","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/soft-sand.png"},
  {"nombre":"Metal Suave","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metal-coat.png"},
  {"nombre":"Roca Puntiaguda","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png"},
  {"nombre":"Incienso Mar","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png"},
  {"nombre":"Incienso Loto","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lax-incense.png"},

  {"nombre":"Placa Llama","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/flame-plate.png"},
  {"nombre":"Placa Aguada","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/splash-plate.png"},
  {"nombre":"Placa Verde","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/meadow-plate.png"},
  {"nombre":"Placa Tóxica","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/toxic-plate.png"},
  {"nombre":"Placa Tierra","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/earth-plate.png"},
  {"nombre":"Placa Piedra","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/stone-plate.png"},
  {"nombre":"Placa Hierro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/iron-plate.png"},
  {"nombre":"Placa Mente","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mind-plate.png"},
  {"nombre":"Placa Cielo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sky-plate.png"},
  {"nombre":"Placa Helada","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/icicle-plate.png"},
  {"nombre":"Placa Puño","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fist-plate.png"},
  {"nombre":"Placa Voltio","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/zap-plate.png"},
  {"nombre":"Placa Insecto","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/insect-plate.png"},
  {"nombre":"Placa Dragón","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/draco-plate.png"},
  {"nombre":"Placa Oscura","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dread-plate.png"},
  {"nombre":"Placa Fantasma","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/spooky-plate.png"},
  {"nombre":"Placa Pixilada","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pixie-plate.png"},

  {"nombre":"Lodo Negro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/black-sludge.png"},
  {"nombre":"Agua Mística","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mystic-water.png"},
  {"nombre":"Campana Concha","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shell-bell.png"},
  {"nombre":"Raíz Grande","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/big-root.png"},
  {"nombre":"Polvo Curativo","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-powder.png"},
  {"nombre":"Hierba Energía","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/power-herb.png"},
  {"nombre":"Hierba Mental","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mental-herb.png"},
  {"nombre":"Polvo de Metal","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metal-powder.png"},
  {"nombre":"Polvo Rápido","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/quick-powder.png"},
  {"nombre":"Ala Veloz","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sharp-beak.png"},

  {"nombre":"Bola Poké","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/poke-ball.png"},
  {"nombre":"Super Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/great-ball.png"},
  {"nombre":"Ultra Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ultra-ball.png"},
  {"nombre":"Master Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/master-ball.png"},
  {"nombre":"Safari Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/safari-ball.png"},
  {"nombre":"Net Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/net-ball.png"},
  {"nombre":"Nido Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nest-ball.png"},
  {"nombre":"Buceo Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dive-ball.png"},
  {"nombre":"Timer Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/timer-ball.png"},
  {"nombre":"Quick Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/quick-ball.png"},
  {"nombre":"Repeat Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/repeat-ball.png"},
  {"nombre":"Luxury Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/luxury-ball.png"},
  {"nombre":"Premier Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/premier-ball.png"},
  {"nombre":"Dusk Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-ball.png"},
  {"nombre":"Heal Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-ball.png"},
  {"nombre":"Cebo Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lure-ball.png"},
  {"nombre":"Level Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/level-ball.png"},
  {"nombre":"Veloz Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fast-ball.png"},
  {"nombre":"Pesada Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heavy-ball.png"},
  {"nombre":"Amor Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/love-ball.png"},
  {"nombre":"Amigo Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/friend-ball.png"},
  {"nombre":"Luna Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moon-ball.png"},
  {"nombre":"Sueño Ball","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dream-ball.png"},

  {"nombre":"Diente Marino","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/deep-sea-tooth.png"},
  {"nombre":"Escama Marina","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/deep-sea-scale.png"},
  {"nombre":"Hueso Grueso","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thick-club.png"},
  {"nombre":"Lupa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/scope-lens.png"},
  {"nombre":"Garra Veloz","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/quick-claw.png"},
  {"nombre":"Roca del Rey","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/king-s-rock.png"},
  {"nombre":"Garra Afilada","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razor-claw.png"},
  {"nombre":"Colmillo Afilado","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razor-fang.png"},
  {"nombre":"Cubo Electro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/electirizer.png"},
  {"nombre":"Imán Mágico","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magmarizer.png"},
  {"nombre":"Protector","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/protector.png"},
  {"nombre":"Tela Espectral","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/reaper-cloth.png"},
  {"nombre":"Escama del Dragón","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dragon-scale.png"},
  {"nombre":"Actualización","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/up-grade.png"},
  {"nombre":"Disco Dudoso","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dubious-disc.png"},

  {"nombre":"Incienso Suerte","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/luck-incense.png"},
  {"nombre":"Incienso Brisa","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wave-incense.png"},
  {"nombre":"Incienso Puro","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pure-incense.png"},
  {"nombre":"Incienso Extraño","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/odd-incense.png"},
  {"nombre":"Incienso Pleno","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-incense.png"},

  {"nombre":"Bicicleta","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/bicycle.png"},
  {"nombre":"Caña de Pescar Vieja","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/old-rod.png"},
  {"nombre":"Caña de Pescar Buena","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/good-rod.png"},
  {"nombre":"Súper Caña de Pescar","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/super-rod.png"},

  {"nombre":"Anillo Mega","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mega-ring.png"},
  {"nombre":"Venusaurita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/venusaurite.png"},
  {"nombre":"Charizardita X","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charizardite-x.png"},
  {"nombre":"Charizardita Y","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charizardite-y.png"},
  {"nombre":"Blastoisita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blastoisinite.png"},
  {"nombre":"Beedrillita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/beedrillite.png"},
  {"nombre":"Pidgeotita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pidgeotite.png"},
  {"nombre":"Alakazita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/alakazite.png"},
  {"nombre":"Slowbrita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/slowbronite.png"},
  {"nombre":"Gengarita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gengarite.png"},
  {"nombre":"Kangaskhanita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kangaskhanite.png"},
  {"nombre":"Pinsirita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pinsirite.png"},
  {"nombre":"Gyaradosita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gyaradosite.png"},
  {"nombre":"Aerodactylita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aerodactylite.png"},
  {"nombre":"Mewtwonita X","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mewtwonite-x.png"},
  {"nombre":"Mewtwonita Y","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mewtwonite-y.png"},
  {"nombre":"Ampharosita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ampharosite.png"},
  {"nombre":"Steelixita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/steelixite.png"},
  {"nombre":"Scizorita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/scizorite.png"},
  {"nombre":"Heracronita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heracronite.png"},
  {"nombre":"Houndoominita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/houndoominite.png"},
  {"nombre":"Tyranitarita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tyranitarite.png"},
  {"nombre":"Sceptilita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sceptilite.png"},
  {"nombre":"Blazikenita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blazikenite.png"},
  {"nombre":"Swampertita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/swampertite.png"},
  {"nombre":"Gardevoirita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gardevoirite.png"},
  {"nombre":"Sablenita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sablenite.png"},
  {"nombre":"Mawilita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mawilite.png"},
  {"nombre":"Aggronita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aggronite.png"},
  {"nombre":"Medichamita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/medichamite.png"},
  {"nombre":"Manectrita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/manectite.png"},
  {"nombre":"Sharpedonita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sharpedonite.png"},
  {"nombre":"Cameruptita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/cameruptite.png"},
  {"nombre":"Altarianita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/altarianite.png"},
  {"nombre":"Banettita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/banettite.png"},
  {"nombre":"Absolita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/absolite.png"},
  {"nombre":"Glalitita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/glalitite.png"},
  {"nombre":"Salamencita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/salamencite.png"},
  {"nombre":"Metagrossita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metagrossite.png"},
  {"nombre":"Latiasita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/latiasite.png"},
  {"nombre":"Latiosita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/latiosite.png"},
  {"nombre":"Lopunnita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lopunnite.png"},
  {"nombre":"Garchompita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/garchompite.png"},
  {"nombre":"Lucarionita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lucarionite.png"},
  {"nombre":"Abomasita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/abomasite.png"},
  {"nombre":"Galladita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/galladite.png"},
  {"nombre":"Audinita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/audinite.png"},
  {"nombre":"Diancita","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/diancite.png"},

  {"nombre":"Cristal Z","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/normalium-z.png"},
  {"nombre":"Dynamax Band","sprite":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dynamax-band.png"}
];

// Las 8 medallas de Kanto (Pokémon Añil = FireRed/LeafGreen), como SVG inline
export const MEDALLAS = [
  { nombre: 'Roca', gimnasio: 'Pewter City', color: '#8a8a8a',
    svg: '<polygon points="12,2 19,6 19,18 12,22 5,18 5,6" fill="#9e9e9e" stroke="#5c5c5c" stroke-width="1.5"/>' },
  { nombre: 'Cascada', gimnasio: 'Cerulean City', color: '#4fa8d8',
    svg: '<path d="M12 2C12 2 5 11 5 15a7 7 0 0014 0c0-4-7-13-7-13z" fill="#5bc0eb" stroke="#2d7aa8" stroke-width="1.5"/>' },
  { nombre: 'Trueno', gimnasio: 'Vermilion City', color: '#f4c430',
    svg: '<polygon points="12,1 14.5,8 22,8.5 16,13 18,20.5 12,16.5 6,20.5 8,13 2,8.5 9.5,8" fill="#ffd23f" stroke="#c79400" stroke-width="1.2"/><circle cx="12" cy="11" r="3.5" fill="#ff8c00"/>' },
  { nombre: 'Arcoíris', gimnasio: 'Celadon City', color: '#ff6b9d',
    svg: '<circle cx="12" cy="6" r="3" fill="#ff4d4d"/><circle cx="18" cy="10" r="3" fill="#ff9d4d"/><circle cx="16" cy="17" r="3" fill="#ffe14d"/><circle cx="8" cy="17" r="3" fill="#4dff7a"/><circle cx="6" cy="10" r="3" fill="#4d9fff"/><circle cx="12" cy="12" r="2.5" fill="#c44dff"/>' },
  { nombre: 'Alma', gimnasio: 'Fuchsia City', color: '#e85d9e',
    svg: '<path d="M12 21s-8-5.2-8-11.5C4 5.9 6.7 3.5 9.5 3.5c1.4 0 2.7.7 3.5 1.9 0.8-1.2 2.1-1.9 3.5-1.9 2.8 0 5.5 2.4 5.5 6 0 6.3-8 11.5-8 11.5z" fill="#f06292" stroke="#ad3a6b" stroke-width="1.2"/>' },
  { nombre: 'Pantano', gimnasio: 'Saffron City', color: '#d4af37',
    svg: '<circle cx="9" cy="12" r="6.5" fill="none" stroke="#d4af37" stroke-width="2.5"/><circle cx="15" cy="12" r="6.5" fill="none" stroke="#f4d35e" stroke-width="2.5"/>' },
  { nombre: 'Volcán', gimnasio: 'Cinnabar Island', color: '#e8492a',
    svg: '<path d="M12 2c2 4-2 5-1 8 1-2 3-2 3-4 2 2 3 5 3 8a7 7 0 11-14 0c0-3 1.5-5.5 3-7 0 2 1 3 2 3 0-3-1-5 4-8z" fill="#ff5733" stroke="#a8331a" stroke-width="1.2"/><circle cx="12" cy="17" r="2" fill="#ffd23f"/>' },
  { nombre: 'Tierra', gimnasio: 'Viridian City', color: '#6b8e4e',
    svg: '<path d="M12 22V8M12 8C8 8 6 5 6 2c4 0 6 2 6 6zM12 8c4 0 6-3 6-6-4 0-6 2-6 6zM12 14c-3 0-5-2-5-2 1 3 3 4 5 4M12 14c3 0 5-2 5-2-1 3-3 4-5 4" fill="none" stroke="#6b8e4e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>' }
];

// Tipos de obtención de Pokémon
export const TIPOS_CAPTURA = [
  'Hierba alta', 'Pesca', 'Surf', 'Cueva', 'Regalo NPC', 'Intercambio NPC',
  'Huevo', 'Fósil', 'Encuentro especial', 'Roca rota (Excavar)', 'Otro'
];
